# coding=utf-8
__author__ = 'Mohamed'


def gerar_form():
    campos = FORM(
        DIV(_id='div_geral',
            *DIV(
                DIV(
                    FIELDSET(
                        LEGEND(_id='lgd_dados_gerais',
                               *'DADOS GERAIS'
                        ),
                        'Nr Registro:',
                        INPUT(_id='nr_registro', _name='nr_registro'),
                        'Matricula HUGG:',
                        INPUT(_id='matricula_hugg', _name='matricula_hugg', requires=IS_NOT_EMPTY()),
                        'Nome: ',
                        INPUT(_id='nome', _name='nome', requires=IS_NOT_EMPTY('Entre com o nome.')),
                        'Idade:',
                        INPUT(_id='idade', _name='idade'),
                        'Sexo:',
                        INPUT(_id='radio_sexo_f',
                              _type='radio',
                              _name='dados_cadastrais_sexo',
                              _value='F'),
                        'F',
                        INPUT(_id='radio_sexo_m',
                              _type='radio',
                              _name='dados_cadastrais_sexo',
                              _value='M'),
                        'M',
                        BR(),
                        'Ficha Nr: ',
                        INPUT(_id='ficha_nr', _name='ficha_nr'),
                        'Data: ',
                        INPUT(_id='data', _name='data'),
                        'Enf:',
                        INPUT(_id='enfermaria', _name='enfermaria'),
                        'Leito:',
                        INPUT(_id='leito', _name='leito'),
                        BR(),
                        'Clinica:',
                        INPUT(_id='clinica', _name='clinica'),
                        'SO:',
                        INPUT(_id='so', _name='so'),
                        BR(),
                        'Altura:',
                        INPUT(_id='altura', _name='altura'),
                        'Peso:',
                        INPUT(_id='peso', _name='peso'),
                        'Temp:',
                        INPUT(_id='temperatura', _name='temperatura'),
                        'Pulso:',
                        INPUT(_id='pulso', _name='pulso'),

                        'ASA:',
                        INPUT(_id='asa', _name='asa'),
                        'E:',
                        INPUT(_id='radio_dados_cadastrais_e_sim',
                              _type='radio',
                              _name='dados_cadastrais_e',
                              _value='T',
                              _checked="true"),
                        'sim',
                        INPUT(_id='radio_dados_cadastrais_e_nao',
                              _type='radio',
                              _name='dados_cadastrais_e',
                              _value='F',
                              _checked="true"),
                        'não',
                        BR(),

                        'Resp.:',
                        INPUT(_id='respiracao', _name='respiracao'),
                        'PA:',
                        INPUT(_id='pa', _name='pa'),
                        HR(),
                        'Diagnóstico',
                        INPUT(_type='text', _id='diagnostico', _name='diagnostico'),
                        'Cirurgia',
                        INPUT(_type='text', _id='dados_cirurgia_anterior', _name='dados_cirurgia_anterior'),
                        HR(),
                        DIV(_id='div_respiratorio',
                            *FIELDSET(
                                LEGEND('RESPIRATÓRIO',
                                       _id='lgd_respiratorio'),
                                TABLE(
                                    TR(
                                        TD(
                                            'Tabagismo',
                                            INPUT(_id='radio_tabag_sim',
                                                  _type='radio',
                                                  _name='tabagismo',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_tabag_nao',
                                                  _type='radio',
                                                  _name='tabagismo',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Asma',
                                            INPUT(_id='radio_asma_sim',
                                                  _type='radio',
                                                  _name='asma',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_asma_nao',
                                                  _type='radio',
                                                  _name='asma',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Tosse / Expectoração',
                                            INPUT(_id='radio_tosse_sim',
                                                  _type='radio',
                                                  _name='tosse',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_tosse_nao',
                                                  _type='radio',
                                                  _name='tosse',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'DPOC / Bronquiectasia',
                                            INPUT(_id='radio_dpoc_sim',
                                                  _type='radio',
                                                  _name='dpoc',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_dpoc_nao',
                                                  _type='radio',
                                                  _name='dpoc',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'BK/Insuf. Respiratória',
                                            INPUT(_id='radio_bk_sim',
                                                  _type='radio',
                                                  _name='bk_insuficiencia',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_bk_nao',
                                                  _type='radio',
                                                  _name='bk_insuficiencia',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Derrame pleural / Emplema',
                                            INPUT(_id='radio_der_pleural_sim',
                                                  _type='radio',
                                                  _name='derrame_pleural',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_der_pleural_nao',
                                                  _type='radio',
                                                  _name='derrame_pleural',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Cir. Torácica',
                                            INPUT(_id='radio_circ_tor_sim',
                                                  _type='radio',
                                                  _name='circunferencia_toraxica',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_circ_tor_nao',
                                                  _type='radio',
                                                  _name='circunferencia_toraxica',
                                                  _value='F'),
                                            'não',
                                        )
                                    )
                                )
                            )
                        ),
                        DIV(_id='div_cardiovascular',
                            *FIELDSET(
                                LEGEND(_id='lgd_cardiovascular',
                                       *'CARDIOVASCULAR'),
                                TABLE(
                                    TR(
                                        TD(
                                            'HAS',
                                            INPUT(_id='radio_has_sim',
                                                  _type='radio',
                                                  _name='has',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_has_nao',
                                                  _type='radio',
                                                  _name='has',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'ICC',
                                            INPUT(_id='radio_icc_sim',
                                                  _type='radio',
                                                  _name='icc',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_icc_nao',
                                                  _type='radio',
                                                  _name='icc',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Anglina',
                                            INPUT(_id='radio_anglina_sim',
                                                  _type='radio',
                                                  _name='anglina',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_anglina_nao',
                                                  _type='radio',
                                                  _name='anglina',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'IAM',
                                            INPUT(_id='radio_iam_sim',
                                                  _type='radio',
                                                  _name='iam',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_iam_nao',
                                                  _type='radio',
                                                  _name='iam',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Valvulopalla',
                                            INPUT(_id='radio_valvulopalla_sim',
                                                  _type='radio',
                                                  _name='valvulopalla',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_valvulopalla_nao',
                                                  _type='radio',
                                                  _name='valvulopalla',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Marcapasso',
                                            INPUT(_id='radio_marcapasso_sim',
                                                  _type='radio',
                                                  _name='marcapasso',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_marcapasso_nao',
                                                  _type='radio',
                                                  _name='marcapasso',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Arritmias',
                                            INPUT(_id='radio_arritmias_sim',
                                                  _type='radio',
                                                  _name='arritmias',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_arritmias_nao',
                                                  _type='radio',
                                                  _name='arritmias',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Insuf. Venosa',
                                            INPUT(_id='radio_insuf_venosa_sim',
                                                  _type='radio',
                                                  _name='insuf_venosa',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_insuf_venosa_nao',
                                                  _type='radio',
                                                  _name='insuf_venosa',
                                                  _value='F'),
                                            'não',
                                        )
                                    )
                                )
                            )
                        ),
                        BR(),
                        FIELDSET(
                            LEGEND(_id='lgd_outros',
                                   *'Outros'),
                            DIV(_id='div_outros_esq',
                                *TABLE(
                                    TR(
                                        TD(
                                            'Diabetes: ',
                                            INPUT(_id='radio_diabetes_sim',
                                                  _type='radio',
                                                  _name='diabetes',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_diabetes_nao',
                                                  _type='radio',
                                                  _name='diabetes',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Hipertireoidismo: ',
                                            INPUT(_id='radio_hipertireoidismo_sim',
                                                  _type='radio',
                                                  _name='hipertireoidismo',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_hipertireoidismo_nao',
                                                  _type='radio',
                                                  _name='hipertireoidismo',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Endocrinopalias: ',
                                            INPUT(_id='radio_endocrinopalias_sim',
                                                  _type='radio',
                                                  _name='endocrinopalias',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_endocrinopalias_nao',
                                                  _type='radio',
                                                  _name='endocrinopalias',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Cirrose: ',
                                            INPUT(_id='radio_cirrose_sim',
                                                  _type='radio',
                                                  _name='cirrose',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_cirrose_nao',
                                                  _type='radio',
                                                  _name='cirrose',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Hepatite A: ',
                                            INPUT(_id='radio_hepa_sim',
                                                  _type='radio',
                                                  _name='hepatite_a',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_hepa_nao',
                                                  _type='radio',
                                                  _name='hepatite_a',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Hepatite B: ',
                                            INPUT(_id='radio_hepb_sim',
                                                  _type='radio',
                                                  _name='hepatite_b',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_hepb_nao',
                                                  _type='radio',
                                                  _name='hepatite_b',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Hepatite C: ',
                                            INPUT(_id='radio_hepc_sim',
                                                  _type='radio',
                                                  _name='hepatite_c',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_hepc_nao',
                                                  _type='radio',
                                                  _name='hepatite_c',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Elilismo: ',
                                            INPUT(_id='radio_elilismo_sim',
                                                  _type='radio',
                                                  _name='elilismo',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_elilismo_nao',
                                                  _type='radio',
                                                  _name='elilismo',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'HIV / SIDA: ',
                                            INPUT(_id='radio_hiv_sim',
                                                  _type='radio',
                                                  _name='hiv',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_hiv_nao',
                                                  _type='radio',
                                                  _name='hiv',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Infecções Oportunistas: ',
                                            INPUT(_id='radio_inf_opor_sim',
                                                  _type='radio',
                                                  _name='infeccoes_oportunistas',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_inf_opor_nao',
                                                  _type='radio',
                                                  _name='infeccoes_oportunistas',
                                                  _value='F'),
                                            'não',
                                        )
                                    ),
                                )
                            ),
                            DIV(_id='div_outros_centro',
                                *TABLE(
                                    *TR(
                                        TD(
                                            TD(
                                                'Insuf. Renal: ',
                                                INPUT(_id='radio_insuf_renal_sim',
                                                      _type='radio',
                                                      _name='insuf_renal',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_insuf_renal_nao',
                                                      _type='radio',
                                                      _name='insuf_renal',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'Hemod. Diálise Peritoneal: ',
                                                INPUT(_id='radio_hemod_sim',
                                                      _type='radio',
                                                      _name='hemodialise_peritoneal',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_hemod_nao',
                                                      _type='radio',
                                                      _name='hemodialise_peritoneal',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'Distúrbios Hemorrágicos: ',
                                                INPUT(_id='radio_dist_hemo_sim',
                                                      _type='radio',
                                                      _name='disturbios_hemorragicos',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_dist_hemo_nao',
                                                      _type='radio',
                                                      _name='disturbios_hemorragicos',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'AVC Prévio: ',
                                                INPUT(_id='radio_avc_previo_sim',
                                                      _type='radio',
                                                      _name='avc_previo',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_avc_previo_nao',
                                                      _type='radio',
                                                      _name='avc_previo',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'D. Psiquiátrica: ',
                                                INPUT(_id='radio_d_psi_sim',
                                                      _type='radio',
                                                      _name='doencas_psiquiatricas',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_d_psi_nao',
                                                      _type='radio',
                                                      _name='doencas_psiquiatricas',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'D. Neuromuscular: ',
                                                INPUT(_id='radio_d_neuro_musc_sim',
                                                      _type='radio',
                                                      _name='doencas_neuromuscular',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_d_neuro_musc_nao',
                                                      _type='radio',
                                                      _name='doencas_neuromuscular',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'D. Reumática: ',
                                                INPUT(_id='radio_d_reuma_sim',
                                                      _type='radio',
                                                      _name='doencas_reumaticas',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_d_reuma_nao',
                                                      _type='radio',
                                                      _name='doencas_reumaticas',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'Alt. Neurológica: ',
                                                INPUT(_id='radio_alt_neuro_sim',
                                                      _type='radio',
                                                      _name='alteracao_neurologica',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_alt_neuro_nao',
                                                      _type='radio',
                                                      _name='alteracao_neurologica',
                                                      _value='F'),
                                                'não',
                                                BR(),
                                                'Hemotransfusão prévia: ',
                                                INPUT(_id='radio_hemo_prev_sim',
                                                      _type='radio',
                                                      _name='hemotransfusao_previa',
                                                      _value='T'),
                                                'sim',
                                                INPUT(_id='radio_hemo_prev_nao',
                                                      _type='radio',
                                                      _name='hemotransfusao_previa',
                                                      _value='F'),
                                                'não',
                                            ),
                                        )
                                    )
                                )
                            ),
                            DIV(_id='div_outros_dir',
                                *TABLE(
                                    TR(
                                        TD(
                                            'Observações Gerais'
                                        )
                                    ),
                                    BR(),
                                    TR(
                                        TD(
                                            TEXTAREA(_id='obs_gerais', _name='obs_gerais')
                                        )
                                    )
                                )
                            ),
                            HR(),
                            'Medicamentos em uso:',
                            INPUT(_type='text', _id='medicamentos_em_uso', _name='medicamentos_em_uso'),
                            BR(),
                            'Alergias:',
                            INPUT(_type='text', _id='alergias', _name='alergias'),
                            BR(),
                            'Cirurgias Prévias / Antecedentes Anestésicos Pessoais e Familiares:',
                            INPUT(_type='text', _id='cirurgias_previas', _name='cirurgias_previas'),
                            HR(),
                            FIELDSET(
                                LEGEND(_id='lgd_vias_aereas',
                                       *'VIAS AÉREAS')
                            ),
                            BR(),
                            DIV(_id='div_cavidade_oral',
                                *FIELDSET(
                                    LEGEND(_id='lgd_cavidade_oral',
                                           *'CAVIDADE ORAL'),
                                    'Mallampati: ',
                                    SELECT(
                                        OPTION('1', _value='MALLAPATI 1', _name='mallampati'),
                                        OPTION('2', _value='MALLAPATI 2', _name='mallampati'),
                                        OPTION('3', _value='MALLAPATI 3', _name='mallampati'),
                                        OPTION('4', _value='MALLAPATI 4', _name='mallampati')
                                    ),

                                    BR(),
                                    'Abertura de boca limitada: ',
                                    INPUT(_id='radio_aber_boca_sim',
                                          _type='radio',
                                          _name='abertura_boca',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_aber_boca_nao',
                                          _type='radio',
                                          _name='abertura_boca',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Dentes Falhos: ',
                                    INPUT(_id='radio_dentes_falhos_sim',
                                          _type='radio',
                                          _name='dentes_falhos',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_dentes_falhos_nao',
                                          _type='radio',
                                          _name='dentes_falhos',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Prótese Sup. - Inf.: ',
                                    INPUT(_id='radio_protese_sim',
                                          _type='radio',
                                          _name='protese',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_protese_nao',
                                          _type='radio',
                                          _name='protese',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Macroglossia: ',
                                    INPUT(_id='radio_macroglossia_sim',
                                          _type='radio',
                                          _name='macroglossia',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_macroglossia_nao',
                                          _type='radio',
                                          _name='macroglossia',
                                          _value='F'),
                                    'não',
                                )
                            ),
                            DIV(_id='div_pescoco',
                                *FIELDSET(
                                    LEGEND(_id='lgd_pescoco',
                                           *'PESCOÇO'),
                                    'Distância Esterno-Mento: ',
                                    INPUT(_type='text', _id='dist_est_mento', _name='distancia_esterno_mento'),
                                    BR(),
                                    'Curto / Longo: ',
                                    INPUT(_type='text', _id='curto_longo', _name='pescoco_curto_longo'),
                                    BR(),
                                    'Mobilidade cervical diminuida: ',
                                    INPUT(_type='text', _id='mob_cervical', _name='mobilidade_cervical'),
                                    BR(),
                                    DIV(
                                        FIELDSET(
                                            'Massa cervical: ',
                                            INPUT(_id='radio_massa_cervical_sim',
                                                  _type='radio',
                                                  _name='massa_cervical',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_massa_cervical_nao',
                                                  _type='radio',
                                                  _name='massa_cervical',
                                                  _value='F'),
                                            'não',
                                        )
                                    ),
                                    BR(),
                                    DIV(
                                        FIELDSET(
                                            'Desvio de traquéia: ',
                                            INPUT(_id='radio_desvio_traqueia_sim',
                                                  _type='radio',
                                                  _name='desvio_traqueia',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_desvio_traqueia_nao',
                                                  _type='radio',
                                                  _name='desvio_traqueia',
                                                  _value='F'),
                                            'não',
                                        )
                                    ),
                                    BR(),
                                    'Distância Mento-Hióide: ',
                                    INPUT(_type='text', _id='dist_mento_hioide', _name='distancia_mento_hiloide'),
                                    BR(),
                                    'Circunferência cervical: ',
                                    INPUT(_type='text', _id='circunferencia_cervical', _name='circunferencia_cervical'),
                                )
                            ),
                            DIV(_id='div_atencao',
                                *FIELDSET(
                                    LEGEND(_id='lgd_atencao',
                                           *'ATENÇÃO'),
                                    'História Prévia Dificuldade de intubação: ',
                                    INPUT(_type='checkbox', _id='chk_hist', _name='dificuldade_intubacao', _value='T'),
                                    BR(),
                                    'Via aérea dificil: ',
                                    INPUT(_type='checkbox', _id='chk_via_aerea_dif', _name='via_aerea_dificil',
                                          _value='T'),
                                    BR(),
                                    'História de anafilaxia: ',
                                    INPUT(_type='checkbox', _id='chk_anafilaxia', _name='historia_de_anafilaxia',
                                          _value='T'),
                                    BR(),
                                    'Estômago Cheio: ',
                                    INPUT(_type='checkbox', _id='chk_estomago_cheio', _name='estomago_cheio',
                                          _value='T'),
                                    BR(),
                                    'Repor. Corticóide: ',
                                    INPUT(_type='checkbox', _id='chk_corticoide', _name='corticoide', _value='T'),
                                    BR(),
                                    'Profilaxia Endocardite Bacteriana: ',
                                    INPUT(_type='checkbox', _id='chk_profilaxia', _name='endocardite_bacteriana',
                                          _value='T'),
                                )
                            ),
                            HR(),
                            DIV(_id='div_exames_laboratoriais',
                                *FIELDSET(
                                    LEGEND(_id='lgd_exames_lab',
                                           *'EXAMES LABORATORIAS'),
                                    "HB: ",
                                    INPUT(_type='text', _id='txt_hb', _name='hb'),
                                    "HT: ",
                                    INPUT(_type='text', _id='txt_ht', _name='ht'),
                                    "HM: ",
                                    INPUT(_type='text', _id='txt_hm', _name='hm'),
                                    "Plaq: ",
                                    INPUT(_type='text', _id='txt_plaq', _name='plaquetas'),
                                    "Gli: ",
                                    INPUT(_type='text', _id='txt_gli', _name='glicose'),
                                    "U: ",
                                    INPUT(_type='text', _id='txt_u', _name='u'),
                                    "CR: ",
                                    INPUT(_type='text', _id='txt_cr', _name='cr'),
                                    "NA+: ",
                                    INPUT(_type='text', _id='txt_na', _name='na'),
                                    "K+: ",
                                    INPUT(_type='text', _id='txt_k', _name='k'),
                                )
                            ),
                            HR(),
                            DIV(_id='div_eventos_operatorios',
                                *FIELDSET(
                                    LEGEND(_id='lgd_eventos_operatorios',
                                           *'EVENTOS OPERATÓRIOS'),
                                    'Duração do Procedimento',
                                    INPUT(_type='text', _id='txt_duracao_procedimento', _name='duracao_procedimento'),
                                    'Duração da Cirurgia',
                                    INPUT(_type='text', _id='txt_duracao_cirurgia', _name='duracao_cirurgia'),
                                )
                            ),
                            BR(),
                            HR(),
                            DIV(_id='div_monitorizacao',
                                *FIELDSET(
                                    LEGEND(_id='lgd_monitorizacao',
                                           *'MONITORIZAÇÃO'),
                                    'Cardioscópio: ',
                                    INPUT(_id='radio_cardioscopio_sim',
                                          _type='radio',
                                          _name='cardioscopio',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_cardioscopio_nao',
                                          _type='radio',
                                          _name='cardioscopio',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Ox. Digital: ',
                                    INPUT(_id='radio_ox_digital_sim',
                                          _type='radio',
                                          _name='ox_digital',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_ox_digital_nao',
                                          _type='radio',
                                          _name='ox_digital',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'PNI: ',
                                    INPUT(_id='radio_pni_sim',
                                          _type='radio',
                                          _name='pni',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_pni_nao',
                                          _type='radio',
                                          _name='pni',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'PAINV: ',
                                    INPUT(_id='radio_painv_sim',
                                          _type='radio',
                                          _name='painv',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_painv_nao',
                                          _type='radio',
                                          _name='painv',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'CAPNÓGRAFO: ',
                                    INPUT(_id='radio_capnografo_sim',
                                          _type='radio',
                                          _name='capnografo',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_capnografo_nao',
                                          _type='radio',
                                          _name='capnografo',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'An. Gases: ',
                                    INPUT(_id='radio_an_gases_sim',
                                          _type='radio',
                                          _name='an_gases',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_an_gases_nao',
                                          _type='radio',
                                          _name='an_gases',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'outros: ',
                                    INPUT(_type='text', _id='outros_monitorizacao', _name='outros_monitorizacao')
                                )
                            ),
                            DIV(_id='div_tecnica',
                                *FIELDSET(
                                    LEGEND(_id='lgd_tecnica',
                                           *'TÉCNICA'),
                                    'Geral: ',
                                    INPUT(_id='radio_tec_geral_sim',
                                          _type='radio',
                                          _name='tec_geral',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_tec_geral_nao',
                                          _type='radio',
                                          _name='tec_geral',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Bloqueio regional ou Plexo: ',
                                    INPUT(_id='radio_plexo_sim',
                                          _type='radio',
                                          _name='plexo',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_plexo_nao',
                                          _type='radio',
                                          _name='plexo',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Bloqueio de Neuroeixo: ',
                                    INPUT(_id='radio_neuroeixo_sim',
                                          _type='radio',
                                          _name='bloqueio_neuroeixo',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_neuroeixo_nao',
                                          _type='radio',
                                          _name='bloqueio_neuroeixo',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Combinada: ',
                                    INPUT(_id='radio_combinada_sim',
                                          _type='radio',
                                          _name='combinada',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_combinada_nao',
                                          _type='radio',
                                          _name='combinada',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Sedação: ',
                                    INPUT(_id='radio_sedacao_sim',
                                          _type='radio',
                                          _name='sedacao',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_sedacao_nao',
                                          _type='radio',
                                          _name='sedacao',
                                          _value='F'),
                                    'não',
                                    BR(),
                                )

                            ),
                            DIV(_id='div_acesso_vias_aereas',
                                *FIELDSET(
                                    LEGEND(_id='lgd_acesso_vias_aereas',
                                           *'ACESSO A VIA AÉREA'),
                                    'Sub Máscara: ',
                                    INPUT(_id='radio_sub_mascara_sim',
                                          _type='radio',
                                          _name='sub_mascara',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_sub_mascara_nao',
                                          _type='radio',
                                          _name='sub_mascara',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Canula Naso: ',
                                    INPUT(_id='radio_can_naso_sim',
                                          _type='radio',
                                          _name='canula_naso',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_can_naso_nao',
                                          _type='radio',
                                          _name='canula_naso',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Canula Orofaringea: ',
                                    INPUT(_id='radio_can_orofaringea_sim',
                                          _type='radio',
                                          _name='canula_orofaringea',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_can_orofaringea_nao',
                                          _type='radio',
                                          _name='canula_orofaringea',
                                          _value='F'),
                                    'não',
                                    BR(),
                                    'Máscara Laríngea: ',
                                    INPUT(_id='radio_masc_laringea_sim',
                                          _type='radio',
                                          _name='mascara_laringea',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_masc_laringea_nao',
                                          _type='radio',
                                          _name='mascara_laringea',
                                          _value='F'),
                                    'não',
                                    DIV(_id='div_masc_laringea',
                                        *FIELDSET(
                                            'NR:',
                                            INPUT(_typr='text', _id='nr_masc_laringea', _name='nr_mascara_laringea')
                                        )),
                                    BR(),
                                    'Intubação Oro Traqueal: ',
                                    INPUT(_id='radio_int_oro_traqueal_sim',
                                          _type='radio',
                                          _name='intubacao_oro_traqueal',
                                          _value='T'),
                                    'sim',
                                    INPUT(_id='radio_int_oro_traqueal_nao',
                                          _type='radio',
                                          _name='intubacao_oro_traqueal',
                                          _value='F'),
                                    'não',
                                    DIV(_id='div_int_oro_traqueal',
                                        *FIELDSET(
                                            'Diâmetro do tubo: ',
                                            INPUT(_typr='text', _id='diametro_tubo', _name='diametro_tubo'),
                                            BR(),
                                            'Tipo naso: ',
                                            INPUT(_id='radio_tipo_naso_sim',
                                                  _type='radio',
                                                  _name='tipo_naso',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_tipo_naso_nao',
                                                  _type='radio',
                                                  _name='tipo_naso',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Tipo aramado: ',
                                            INPUT(_id='radio_tipo_aramado_sim',
                                                  _type='radio',
                                                  _name='tipo_aramado',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_tipo_aramado_nao',
                                                  _type='radio',
                                                  _name='tipo_aramado',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Tipo dupla luz: ',
                                            INPUT(_id='radio_tipo_dupla_luz_sim',
                                                  _type='radio',
                                                  _name='dupla_luz',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_tipo_dupla_luz_nao',
                                                  _type='radio',
                                                  _name='dupla_luz',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Tipo balao: ',
                                            INPUT(_id='radio_balao_sim',
                                                  _type='radio',
                                                  _name='balao',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_balao_nao',
                                                  _type='radio',
                                                  _name='balao',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Laringoscopia: ',
                                            INPUT(_id='radio_laringoscopia_sim',
                                                  _type='radio',
                                                  _name='laringoscopia',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_laringoscopia_nao',
                                                  _type='radio',
                                                  _name='laringoscopia',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Broncofibroscopia: ',
                                            INPUT(_id='radio_broncofibroscopia_sim',
                                                  _type='radio',
                                                  _name='broncofibroscopia',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_broncofibroscopia_nao',
                                                  _type='radio',
                                                  _name='broncofibroscopia',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Estilete luminoso: ',
                                            INPUT(_id='radio_est_luminoso_sim',
                                                  _type='radio',
                                                  _name='estilete_luminoso',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_est_luminoso_nao',
                                                  _type='radio',
                                                  _name='estilete_luminoso',
                                                  _value='F'),
                                            'não',
                                            BR(),
                                            'Videolaringoscopia: ',
                                            INPUT(_id='radio_videolaringoscopia_sim',
                                                  _type='radio',
                                                  _name='videolaringoscopia',
                                                  _value='T'),
                                            'sim',
                                            INPUT(_id='radio_videolaringoscopia_nao',
                                                  _type='radio',
                                                  _name='videolaringoscopia',
                                                  _value='F'),
                                            'não',
                                        )
                                    ),
                                    BR(),
                                )
                            ),
                            HR(),
                            BR(),
                            DIV(_id='div_agentes',
                                *FIELDSET(
                                    LEGEND(_id='lgd_agentes',
                                           *'Agentes'),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente1', _name='agente1', _default=None),
                                        INPUT(_type='button', _id='btn_inclui_agente1_pgincluir',
                                              _value='+', _onclick='chama_segundo_incluir()'),
                                        _id='div_primero_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente2', _name='agente2'),
                                        INPUT(_type='hidden', _id='agente2_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente2_incluir', _value='-',
                                              _onclick='esconde_segundo_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente2_incluir', _value='+',
                                              _onclick='chama_terceiro_incluir()'),
                                        _id='div_segundo_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente3', _name='agente3'),
                                        INPUT(_type='hidden', _id='agente3_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente3_incluir', _value='-',
                                              _onclick='esconde_terceiro_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente3_incluir', _value='+',
                                              _onclick='chama_quarto_incluir()'),
                                        _id='div_terceiro_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente4', _name='agente4'),
                                        INPUT(_type='hidden', _id='agente4_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente4_incluir', _value='-',
                                              _onclick='esconde_quarto_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente4_incluir', _value='+',
                                              _onclick='chama_quinto_incluir()'),
                                        _id='div_quarto_agente_incluir'),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente5', _name='agente5'),
                                        INPUT(_type='hidden', _id='agente5_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente5_incluir', _value='-',
                                              _onclick='esconde_quinto_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente5_incluir', _value='+',
                                              _onclick='chama_sexto_incluir()'),
                                        _id='div_quinto_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente6', _name='agente6'),
                                        INPUT(_type='hidden', _id='agente6_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente6_incluir', _value='-',
                                              _onclick='esconde_sexto_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente6_incluir', _value='+',
                                              _onclick='chama_setimo_incluir()'),
                                        _id='div_sexto_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente7', _name='agente7'),
                                        INPUT(_type='hidden', _id='agente7_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente7_incluir', _value='-',
                                              _onclick='esconde_setimo_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente7_incluir', _value='+',
                                              _onclick='chama_oitavo_incluir()'),
                                        _id='div_setimo_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente8', _name='agente8'),
                                        INPUT(_type='hidden', _id='agente8_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente8_incluir', _value='-',
                                              _onclick='esconde_oitavo_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente8_incluir', _value='+',
                                              _onclick='chama_nono_incluir()'),
                                        _id='div_oitavo_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente9', _name='agente9'),
                                        INPUT(_type='hidden', _id='agente9_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente9_incluir', _value='-',
                                              _onclick='esconde_nono_incluir()'),
                                        INPUT(_type='button', _id='btn_inclui_agente9_incluir', _value='+',
                                              _onclick='chama_decimo_incluir()'),
                                        _id='div_nono_agente_incluir'
                                    ),
                                    DIV('Nome: ',
                                        INPUT(_type='text', _id='agente10', _name='agente10'),
                                        INPUT(_type='hidden', _id='agente10_controle_incluir'),
                                        INPUT(_type='button', _id='btn_esconder_agente10_incluir', _value='-',
                                              _onclick='esconde_decimo_incluir()'),
                                        _id='div_decimo_agente_incluir'
                                    ),
                                )),
                            BR(),
                            HR(),
                            FIELDSET(
                                LEGEND(_id='lgd_dados_cirurgia',
                                       *'DADOS CIRURGIA'),
                                'Cirurgia: ',
                                INPUT(_type='text', _id='cirurgia', _name='cirurgia'),
                                'Anestesista: ',
                                INPUT(_type='text', _id='anestesia', _name='anestesia'),
                                'Cirurgião: ',
                                INPUT(_type='text', _id='cirurgiao', _name='cirurgiao'),
                            ),
                            BR(),
                            HR()
                        )
                    )
                )
            )
        ),
        INPUT(_type='submit')
    )
    return campos


def index():
    teste = ''
    aqui = ''
    nome = request.vars.nome

    form_incluir = gerar_form()

    if form_incluir.accepts(request.vars):

        enfermaria = request.vars.enfermaria
        if (enfermaria == ''):
            enfermaria = 'null'
        leito = request.vars.leito
        if (leito == ''):
            leito = 'null'
        asa = request.vars.asa
        if (asa == ''):
            asa = 'null'
        clinica = request.vars.clinica
        if (clinica == ''):
            clinica = 'null'
        so = request.vars.so
        if (so == ''):
            so = 'null'
        pa = request.vars.pa
        if (pa == ''):
            pa = 'null'
        diagnostico = request.vars.diagnostico
        if (diagnostico == ''):
            diagnostico = 'null'
        dados_cirurgia_anterior = request.vars.dados_cirurgia_anterior
        if (dados_cirurgia_anterior == ''):
            dados_cirurgia_anterior = 'null'
        obs_gerais = request.vars.obs_gerais
        if (obs_gerais == ''):
            obs_gerais = 'null'
        medicamentos_em_uso = request.vars.medicamentos_em_uso
        if (medicamentos_em_uso == ''):
            medicamentos_em_uso = 'null'
        alergias = request.vars.alergias
        if (alergias == ''):
            alergias = 'null'
        cirurgias_previas = request.vars.cirurgias_previas
        if (cirurgias_previas == ''):
            cirurgias_previas = 'null'
        distancia_esterno_mento = request.vars.distancia_esterno_mento
        if (distancia_esterno_mento == ''):
            distancia_esterno_mento = 'null'
        pescoco_curto_longo = request.vars.pescoco_curto_longo
        if (pescoco_curto_longo == ''):
            pescoco_curto_longo = 'null'
        mobilidade_cervical = request.vars.mobilidade_cervical
        if (mobilidade_cervical == ''):
            mobilidade_cervical = 'null'
        distancia_mento_hiloide = request.vars.distancia_mento_hiloide
        if (distancia_mento_hiloide == ''):
            distancia_mento_hiloide = 'null'
        circunferencia_cervical = request.vars.circunferencia_cervical
        if (circunferencia_cervical == ''):
            circunferencia_cervical = 'null'
        hb = request.vars.hb
        if (hb == ''):
            hb = 'null'
        ht = request.vars.ht
        if (ht == ''):
            ht = 'null'
        hm = request.vars.hm
        if (hm == ''):
            hm = 'null'
        plaquetas = request.vars.plaquetas
        if (plaquetas == ''):
            plaquetas = 'null'
        glicose = request.vars.glicose
        if (glicose == ''):
            glicose = 'null'
        u = request.vars.u
        if (u == ''):
            u = 'null'
        cr = request.vars.cr
        if (cr == ''):
            cr = 'null'
        na = request.vars.na
        if (na == ''):
            na = 'null'
        k = request.vars.k
        if (k == ''):
            k = 'null'
        duracao_procedimento = request.vars.duracao_procedimento
        if (duracao_procedimento == ''):
            duracao_procedimento = 'null'
        duracao_cirurgia = request.vars.duracao_cirurgia
        if (duracao_cirurgia == ''):
            duracao_cirurgia = 'null'
        outros_monitorizacao = request.vars.outros_monitorizacao
        if (outros_monitorizacao == ''):
            outros_monitorizacao = 'null'
        nr_mascara_laringea = request.vars.nr_mascara_laringea
        if (nr_mascara_laringea == ''):
            nr_mascara_laringea = 'null'
        agente1 = request.vars.agente1
        if (agente1 == ''):
            agente1 = 'null'
        agente2 = request.vars.agente2
        if (agente2 == ''):
            agente2 = 'null'
        agente3 = request.vars.agente3
        if (agente3 == ''):
            agente3 = 'null'
        agente4 = request.vars.agente4
        if (agente4 == ''):
            agente4 = 'null'
        agente5 = request.vars.agente5
        if (agente5 == ''):
            agente5 = 'null'
        agente6 = request.vars.agente6
        if (agente6 == ''):
            agente6 = 'null'
        agente7 = request.vars.agente7
        if (agente7 == ''):
            agente7 = 'null'
        agente8 = request.vars.agente8
        if (agente8 == ''):
            agente8 = 'null'
        agente9 = request.vars.agente9
        if (agente9 == ''):
            agente9 = 'null'
        agente10 = request.vars.agente10
        if (agente10 == ''):
            agente10 = 'null'
        cirurgia = request.vars.cirurgia
        if (cirurgia == ''):
            cirurgia = 'null'
        anestesia = request.vars.anestesia
        if (anestesia == ''):
            anestesia = 'null'
        cirurgiao = request.vars.cirurgiao
        if (cirurgiao == ''):
            cirurgiao = 'null'

        try:
            teste = db.paciente.insert(nr_registro=request.vars.nr_registro,
                                       matricula_hugg=request.vars.matricula_hugg,
                                       nome=request.vars.nome,
                                       # nome=nome,
                                       data=request.vars.data,
                                       ficha_nr=request.vars.ficha_nr,
                                       #enfermaria=request.vars.enfermaria,
                                       enfermaria=enfermaria,
                                       #leito=request.vars.leito,
                                       leito=leito,
                                       idade=request.vars.idade,
                                       #asa=request.vars.asa,
                                       asa=asa,
                                       #clinica=request.vars.clinica,
                                       clinica=clinica,
                                       #so=request.vars.so,
                                       so=so,
                                       dados_cadastrais_e=request.vars.dados_cadastrais_e,
                                       dados_cadastrais_sexo=request.vars.dados_cadastrais_sexo,
                                       altura=request.vars.altura,
                                       peso=request.vars.peso,
                                       temperatura=request.vars.temperatura,
                                       pulso=request.vars.pulso,
                                       respiracao=request.vars.respiracao,
                                       #pa=request.vars.pa,
                                       pa=pa,
                                       #diagnostico=request.vars.diagnostico,
                                       diagnostico=diagnostico,
                                       #dados_cirurgia_anterior=request.vars.dados_cirurgia_anterior,
                                       dados_cirurgia_anterior=dados_cirurgia_anterior,
                                       tabagismo=request.vars.tabagismo,
                                       asma=request.vars.asma,
                                       tosse=request.vars.tosse,
                                       dpoc=request.vars.dpoc,
                                       bk_insuficiencia=request.vars.bk_insuficiencia,
                                       derrame_pleural=request.vars.derrame_pleural,
                                       circunferencia_toraxica=request.vars.circunferencia_toraxica,
                                       has=request.vars.has,
                                       icc=request.vars.icc,
                                       anglina=request.vars.anglina,
                                       iam=request.vars.iam,
                                       valvulopalla=request.vars.valvulopalla,
                                       marcapasso=request.vars.marcapasso,
                                       arritmias=request.vars.arritmias,
                                       insuf_venosa=request.vars.insuf_venosa,
                                       diabetes=request.vars.diabetes,
                                       hipertireoidismo=request.vars.hipertireoidismo,
                                       endocrinopalias=request.vars.endocrinopalias,
                                       cirrose=request.vars.cirrose,
                                       hepatite_a=request.vars.hepatite_a,
                                       hepatite_b=request.vars.hepatite_b,
                                       hepatite_c=request.vars.hepatite_c,
                                       elilismo=request.vars.elilismo,
                                       hiv=request.vars.elilismo,
                                       infeccoes_oportunistas=request.vars.infeccoes_oportunistas,
                                       insuf_renal=request.vars.insuf_renal,
                                       hemodialise_peritoneal=request.vars.hemodialise_peritoneal,
                                       disturbios_hemorragicos=request.vars.disturbios_hemorragicos,
                                       avc_previo=request.vars.avc_previo,
                                       doencas_psiquiatricas=request.vars.doencas_psiquiatricas,
                                       doencas_neuromuscular=request.vars.doencas_neuromuscular,
                                       doencas_reumaticas=request.vars.doencas_reumaticas,
                                       alteracao_neurologica=request.vars.alteracao_neurologica,
                                       hemotransfusao_previa=request.vars.hemotransfusao_previa,
                                       #obs_gerais=request.vars.obs_gerais,
                                       obs_gerais=obs_gerais,
                                       #medicamentos_em_uso=request.vars.medicamentos_em_uso,
                                       medicamentos_em_uso=medicamentos_em_uso,
                                       #alergias=request.vars.alergias,
                                       alergias=alergias,
                                       #cirurgias_previas=request.vars.cirurgias_previas,
                                       cirurgias_previas=cirurgias_previas,
                                       mallampati=request.vars.mallampati,
                                       abertura_boca=request.vars.abertura_boca,
                                       dentes_falhos=request.vars.dentes_falhos,
                                       protese=request.vars.protese,
                                       macroglossia=request.vars.macroglossia,
                                       #distancia_esterno_mento=request.vars.distancia_esterno_mento,
                                       distancia_esterno_mento=distancia_esterno_mento,
                                       #pescoco_curto_longo=request.vars.pescoco_curto_longo,
                                       pescoco_curto_longo=pescoco_curto_longo,
                                       #mobilidade_cervical=request.vars.mobilidade_cervical,
                                       mobilidade_cervical=mobilidade_cervical,
                                       massa_cervical=request.vars.massa_cervical,
                                       desvio_traqueia=request.vars.desvio_traqueia,
                                       #distancia_mento_hiloide=request.vars.distancia_mento_hiloide,
                                       distancia_mento_hiloide=distancia_mento_hiloide,
                                       #circunferencia_cervical=request.vars.circunferencia_cervical,
                                       circunferencia_cervical=circunferencia_cervical,
                                       dificuldade_intubacao=request.vars.dificuldade_intubacao,
                                       via_aerea_dificil=request.vars.via_aerea_dificil,
                                       historia_de_anafilaxia=request.vars.historia_de_anafilaxia,
                                       estomago_cheio=request.vars.estomago_cheio,
                                       corticoide=request.vars.corticoide,
                                       endocardite_bacteriana=request.vars.endocardite_bacteriana,
                                       #hb=request.vars.hb,
                                       hb=hb,
                                       #ht=request.vars.ht,
                                       ht=ht,
                                       #hm=request.vars.hm,
                                       hm=hm,
                                       #plaquetas=request.vars.plaquetas,
                                       plaquetas=plaquetas,
                                       #glicose=request.vars.glicose,
                                       glicose=glicose,
                                       #u=request.vars.u,
                                       u=u,
                                       #cr=request.vars.cr,
                                       cr=cr,
                                       #na=request.vars.na,
                                       na=na,
                                       #k=request.vars.k,
                                       k=k,
                                       #duracao_procedimento=request.vars.duracao_procedimento,
                                       duracao_procedimento=duracao_procedimento,
                                       #duracao_cirurgia=request.vars.duracao_cirurgia,
                                       duracao_cirurgia=duracao_cirurgia,
                                       cardioscopio=request.vars.cardioscopio,
                                       ox_digital=request.vars.ox_digital,
                                       pni=request.vars.pni,
                                       painv=request.vars.painv,
                                       capnografo=request.vars.capnografo,
                                       an_gases=request.vars.an_gases,
                                       #outros_monitorizacao=request.vars.outros_monitorizacao,
                                       outros_monitorizacao=outros_monitorizacao,
                                       tec_geral=request.vars.tec_geral,
                                       plexo=request.vars.plexo,
                                       bloqueio_neuroeixo=request.vars.bloqueio_neuroeixo,
                                       combinada=request.vars.combinada,
                                       sedacao=request.vars.sedacao,
                                       sub_mascara=request.vars.sub_mascara,
                                       canula_naso=request.vars.canula_naso,
                                       canula_orofaringea=request.vars.canula_orofaringea,
                                       mascara_laringea=request.vars.mascara_laringea,
                                       #nr_mascara_laringea=request.vars.nr_mascara_laringea,
                                       nr_mascara_laringea=nr_mascara_laringea,
                                       intubacao_oro_traqueal=request.vars.intubacao_oro_traqueal,
                                       #agente1=request.vars.agente1,
                                       agente1=agente1,
                                       #agente2=request.vars.agente2,
                                       agente2=agente2,
                                       #agente3=request.vars.agente3,
                                       agente3=agente3,
                                       #agente4=request.vars.agente4,
                                       agente4=agente4,
                                       #agente5=request.vars.agente5,
                                       agente5=agente5,
                                       #agente6=request.vars.agente6,
                                       agente6=agente6,
                                       #agente7=request.vars.agente7,
                                       agente7=agente7,
                                       #agente8=request.vars.agente8,
                                       agente8=agente8,
                                       #agente9=request.vars.agente9,
                                       agente9=agente9,
                                       #agente10=request.vars.agente10,
                                       agente10=agente10,
                                       tipo_naso=request.vars.tipo_naso,
                                       tipo_aramado=request.vars.tipo_aramado,
                                       dupla_luz=request.vars.dupla_luz,
                                       balao=request.vars.balao,
                                       laringoscopia=request.vars.laringoscopia,
                                       broncofibroscopia=request.vars.broncofibroscopia,
                                       estilete_luminoso=request.vars.estilete_luminoso,
                                       videolaringoscopia=request.vars.videolaringoscopia,
                                       #cirurgia=request.vars.cirurgia,
                                       cirurgia=cirurgia,
                                       #anestesia=request.vars.anestesia,
                                       anestesia=anestesia,
                                       #cirurgiao=request.vars.cirurgiao)
                                       cirurgiao=cirurgiao)

            session.flash = T(
                'Usúario ' + request.vars.nome + ' de matrícula ' + request.vars.matricula_hugg + ' e número de registro ' + request.vars.nr_registro + ' incluido com sucesso!')

            redirect('index')

        except Exception, e:
            raise e
            response.flash = T("Não foi possível realizar a inclusão dos dados.")

            # teste = request.vars

    return dict(formulario=form_incluir, teste=teste)